<SM>:
    Page1:
        name: 'page1'
    Page2:
        name: 'page2'
<Page1>:
    mdlistid:mdlistid
    MDBottomNavigation:
        MDBottomNavigationItem:
            name: 'devices'
            text: 'Devices'
            ScrollView:
                MDList:
                    id: mdlistid
                    Button:
                        text: 'Seek Devices'
                        on_release: root.seek_devices()

<Page2>:
    Button:
        text: 'Go Page 1'
        size_hint:None,None
        size: 250,250
        pos_hint: {'center_x':.5,'center_y':.5}
        on_release: root.manager.current = 'page1'